name: Update Docs and Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  update-docs:
    name: Generate and Deploy Docs
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx_book_theme sphinx_markdown_tables recommonmark nbsphinx sphinx_togglebutton

    # Build the documentation
    - name: Build Docs
      run: |
        cd docs
        make clean html

    # Commit and push updated docs
    - name: Commit and Push Docs
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add docs
        git commit -m "Update docs after push to master"
        git push origin master

  deploy-docs:
    name: Deploy Docs to Website
    needs: update-docs
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Deploy updated documentation
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
